# Generated by Django 4.1 on 2022-08-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quantity', models.IntegerField()),
                ('bsale', models.IntegerField()),
                ('aka', models.CharField(max_length=60)),
            ],
        ),
    ]
